Production Issue: Generic errors when adding new shipments and Filter the "Associate Gateway" dropdown
TransparentPath/buildly-react-template pull request #282
Opened 2022-02-04 16:14 UTC by yasmin2496

## Purpose
_Fix Generic errors when adding new shipments_
_Filter the "Associate Gateway" dropdown_

## Ticket number
_#281_
_#275_

2022-02-07 09:44 UTC, RadhikaPPatel requested changes

2022-02-07 09:44 UTC, RadhikaPPatel commented on src/pages/SensorsGateway/Constants.js
> +  if (shipmentFormData.custody_info.length > 0) {
This is breaking. It needs to be `shipmentFormData.custody_info && shipmentFormData.custody_info.length > 0`.

Also, there are some errors coming to the console. So please resolve those as well.

2022-02-07 11:23 UTC, yasmin2496 commented on src/pages/SensorsGateway/Constants.js
> +  if (shipmentFormData.custody_info.length > 0) {
@RadhikaPPatel Can you share what the errors are on the console

2022-02-08 10:10 UTC, RadhikaPPatel approved these changes
Looks good. Everything checked below is working as expected.

- [x] Checked creation of new shipment. Working fine.
- [x] Checked gateway options with and without a custodian attached.

2022-02-08 10:24 UTC, merged