Feedback for Acceptance testing - v0.4.8
TransparentPath/buildly-react-template pull request #308
Opened 2022-03-15 15:22 UTC by yasmin2496

## Purpose
_Work on the feedback recevied after Acceptance testing - v0.4.8_

## Ticket number
_#305_

closing #305

2022-03-15 16:18 UTC, SiddharthBhansali13 approved these changes

2022-03-16 06:11 UTC, RadhikaPPatel requested changes

2022-03-16 06:11 UTC, RadhikaPPatel commented on src/pages/Shipment/ShipmentConstants.js
> +        { shipment_id: editedShipment.shipment_uuid }), 'create_date', 'asc')[0];
Why do we need the first element in orderBy?

2022-03-16 09:19 UTC, yasmin2496 commented on src/pages/Shipment/ShipmentConstants.js
> +        { shipment_id: editedShipment.shipment_uuid }), 'create_date', 'asc')[0];
@RadhikaPPatel To know what the first custody is. Apparently, the requirement is to show gateways for the first custody, not alphabetically but on basis of time

2022-03-16 09:25 UTC, RadhikaPPatel requested changes

2022-03-16 09:25 UTC, RadhikaPPatel commented on src/pages/Shipment/components/custodian-info/CustodianInfo.js
> +    ) || (_.isEmpty(custodyData) && custodianData && custodianData.length && shipmentFormData)) {
Instead of adding this extra check how about, we remove only the line custodyData.length?

2022-03-16 09:38 UTC, yasmin2496 commented on src/pages/Shipment/components/custodian-info/CustodianInfo.js
> +    ) || (_.isEmpty(custodyData) && custodianData && custodianData.length && shipmentFormData)) {
Tried doing it this is the same error they reported the custodains aren't getting updated if we delete those

2022-03-16 10:27 UTC, RadhikaPPatel commented on src/pages/Shipment/components/custodian-info/CustodianInfo.js
> +    ) || (_.isEmpty(custodyData) && custodianData && custodianData.length && shipmentFormData)) {
Okay no problem

2022-03-16 10:27 UTC, RadhikaPPatel approved these changes
Code looks fine

2022-03-16 13:20 UTC, yasmin2496 commented
@RadhikaPPatel I have done changes as per latest feedback received. Could you review it once?

2022-03-17 06:54 UTC, merged