Admin Panel Scroll Issue & Core User's Organization Name Bug
TransparentPath/buildly-react-template pull request #314
Opened 2022-03-21 08:30 UTC by SiddharthBhansali13

## Purpose
- Fix error form helper text color.
- Fix scroll issue on accordions in admin panel.
- Fix a bug which prevents a user's organization name to be populated after permission or active status update.

## Ticket number
Closes #310 & #311.

2022-03-21 09:22 UTC, RadhikaPPatel requested changes
Please check the comments

2022-03-21 09:22 UTC, RadhikaPPatel commented on src/pages/UserManagement/Users/Users.js
> +                      template: () => (
Why is the parameter row removed?

2022-03-21 09:22 UTC, RadhikaPPatel commented on src/pages/UserManagement/Users/Users.js
> +                            {organization.name ?? organization_name}
I guess it should be `organization?.name || organization_name`

2022-03-21 09:22 UTC, RadhikaPPatel commented on src/pages/UserManagement/Users/Users.js
> +                      template: () => (
Why is the parameter row removed?

2022-03-21 09:24 UTC, SiddharthBhansali13 commented on src/pages/UserManagement/Users/Users.js
> +                      template: () => (
The `row` parameter wasn't being used in the callback. Unused variable. Should I add it back?

2022-03-21 09:24 UTC, SiddharthBhansali13 commented on src/pages/UserManagement/Users/Users.js
> +                            {organization.name ?? organization_name}
Both will work the same. `??` will find the first non-null or non-undefined value and print it. Should I change?

2022-03-21 09:25 UTC, SiddharthBhansali13 commented on src/pages/UserManagement/Users/Users.js
> +                      template: () => (
Unused variable in the callback function.

2022-03-22 07:20 UTC, RadhikaPPatel approved these changes
Looks good

2022-03-22 10:39 UTC, yasmin2496 approved these changes

2022-03-22 10:39 UTC, merged