rewrite failed unit test cases
TransparentPath/buildly-react-template pull request #320
Opened 2022-03-28 09:39 UTC by MounikaReddy15

## Purpose
_Rewrite unit test cases which are failing_

## Ticket number
#318

2022-03-30 13:22 UTC, yasmin2496 commented on src/redux/custodian/reducers/custodian.reducer.js
> +        loading: false,
@MounikaReddy15 Can you revert this? The change here done is due to some issues with workflow. Also can you add a comment mentioning **the change is done so that even after custody data is loaded subsequent data be also loaded**

2022-03-30 13:29 UTC, yasmin2496 commented on src/redux/custodian/reducers/custodian.reducer.test.js
> +      custodianData: [undefined],
@MounikaReddy15 There are missing test cases for "UPDATE_CUSTODIAN"

2022-03-30 13:43 UTC, yasmin2496 requested changes
1. Missing unit test cases for custodian.reducer
2. Some of the loaded states are set to false to make code function in certain manner. Need to replicate the same in test files
3. While running test after fixing point 2 on local, 1 test suite is failing
![image](https://user-images.githubusercontent.com/61192422/160848894-655d4178-87fc-4364-89a5-bfff578fd34c.png)

2022-03-31 11:37 UTC, MounikaReddy15 commented on src/redux/custodian/reducers/custodian.reducer.js
> +        loading: false,
Added

2022-03-31 11:37 UTC, MounikaReddy15 commented on src/redux/custodian/reducers/custodian.reducer.test.js
> +      custodianData: [undefined],
Added missing test cases

2022-03-31 11:39 UTC, MounikaReddy15 commented
> 1. Missing unit test cases for custodian.reducer
> 2. Some of the loaded states are set to false to make code function in certain manner. Need to replicate the same in test files
> 3. While running test after fixing point 2 on local, 1 test suite is failing
>    ![image](https://user-images.githubusercontent.com/61192422/160848894-655d4178-87fc-4364-89a5-bfff578fd34c.png)

Only when all the import paths are changes to relative paths test suites are successful, so I change all the paths to relative paths

2022-04-06 11:02 UTC, yasmin2496 approved these changes

2022-04-06 11:10 UTC, merged