Feat/user flow
TransparentPath/buildly-react-template pull request #420
Opened 2024-03-19 15:10 UTC by TanmayJain92

## Purpose
Add new user flow UI and its respected functionality.

2024-03-21 13:50 UTC, TanmayJain92 commented on src/pages/Login/Login.js
> +  const email = useInput(localStorage.getItem('email') || '', { required: true });
There's a option for Remember Email so I'm saving it in local storage when we checked the checkbox and click submit and removing when uncheck the checkbox.

2024-03-22 07:45 UTC, patelradhika commented
Make Verification page more like Forgot Password or Reset Password Page with Logo.
![image](https://github.com/TransparentPath/buildly-react-template/assets/64517071/e4ff2ff9-178f-4e87-856f-ce24114174d3)
![image](https://github.com/TransparentPath/buildly-react-template/assets/64517071/be5cde30-dc86-4266-9fc1-ecc9bbb0daac)

2024-03-22 07:47 UTC, patelradhika commented
When Admin is trying to invite the user, we cannot see User Roles. See the screenshot below.
![image](https://github.com/TransparentPath/buildly-react-template/assets/64517071/82dccd49-726e-416a-a63f-ea51529777e3)

2024-03-22 14:23 UTC, TanmayJain92 commented
All above things done.

2024-03-26 08:58 UTC, patelradhika requested changes
Final few changes

2024-03-26 08:58 UTC, patelradhika commented on src/pages/Shipment/CreateShipment.js
>    );
Add template and organization in the check please. Otherwise it will not be correct value of the setting.
![image](https://github.com/TransparentPath/buildly-react-template/assets/64517071/be6a90f3-cdfc-4548-af6e-8771e8652d26)

2024-03-26 08:58 UTC, patelradhika commented on src/pages/Login/Login.js
> +  const [isChecked, setChecked] = useState(!!localStorage.getItem('username') || false);
It should be email not username

2024-03-26 09:52 UTC, patelradhika approved these changes
Looks good

2024-03-26 09:53 UTC, merged