Fix battery level in shipment section
TransparentPath/buildly-react-template pull request #443
Opened 2024-05-07 13:53 UTC by TanmayJain92

## Purpose
Fix tracker battery level in shipment page.

2024-05-07 14:05 UTC, patelradhika requested changes

2024-05-07 14:05 UTC, patelradhika commented on src/utils/constants.js
> +            (obj) => moment(obj.report_entry.report_timestamp),
Sort by activation_date

2024-05-07 14:06 UTC, patelradhika commented
@TanmayJain92 Also add bump patch version in package.json file

2024-05-08 09:00 UTC, TanmayJain92 commented on src/utils/constants.js
> +            (obj) => moment(obj.report_entry.report_timestamp),
done

2024-05-08 09:00 UTC, TanmayJain92 commented
> @TanmayJain92 Also add bump patch version in package.json file
Done.

2024-05-09 08:00 UTC, patelradhika approved these changes
Looks good

2024-05-09 08:00 UTC, merged