Add resellers-customers, localization and guidance text
TransparentPath/buildly-react-template pull request #455
Opened 2024-05-29 14:41 UTC by TanmayJain92

## Purpose
1. Added resellers and their customers organization flow.
2. Added localization in the app.
3. Added tracker transmission and measurement guidance text while creating shipments.

2024-05-30 09:04 UTC, patelradhika requested changes

2024-05-30 09:04 UTC, patelradhika commented on src/react-query/mutations/authUser/updateUserMutation.js
> +        window.location.reload();
Why location reload on update user? Can't you just invalidate the queries and fetch again?

2024-05-30 09:04 UTC, patelradhika commented on src/index.js
> -import './i18n';
If you are removing i18n remove all related files that are not used anywhere

2024-05-30 09:19 UTC, patelradhika commented
![image](https://github.com/TransparentPath/buildly-react-template/assets/64517071/1c521473-c7c2-4327-bd4a-5ee5459fe73a)

Why is there a line coming at the bottom? Please fix this

2024-05-30 10:30 UTC, TanmayJain92 commented on src/react-query/mutations/authUser/updateUserMutation.js
> +        window.location.reload();
This is for applying localization. Also window will reload only when I'm passing the user_language.

2024-05-30 10:30 UTC, TanmayJain92 commented on src/index.js
> -import './i18n';
Done

2024-05-31 10:43 UTC, patelradhika approved these changes

2024-05-31 10:43 UTC, merged