Add organization filter in GET endpoints
TransparentPath/buildly-react-template pull request #49
Opened 2020-12-08 12:07 UTC by yasmin2496

## Purpose
_To support multi tenancy, filter by organization uuid_

## Issue Link
_https://github.com/TransparentPath/buildly-react-template/issues/43_

2020-12-08 12:12 UTC, yasmin2496 commented on src/midgard/pages/Custodians/Custodians.js
> +          `${environment.API_URL}custodian/custodian/?organization_uuid=${organization}`,
Here, an API call is made directly from the page also there is a saga definition for the same. @andrewshortall @glind Should we follow the same design or can we go ahead and do code cleanup here

2020-12-12 14:35 UTC, andrewshortall commented on src/midgard/pages/Custodians/Custodians.js
> +          `${environment.API_URL}custodian/custodian/?organization_uuid=${organization}`,
We can do a code cleanup

2021-01-06 13:59 UTC, RadhikaPPatel commented on src/midgard/pages/Custodians/Custodians.js
> +let organization = localStorage.getItem("currentUser") ? JSON.parse(localStorage.getItem("currentUser")).organization.organization_uuid : '';
Remove the check as after login currentUser will be there in localStorage. It will only be removed on logout.

2021-01-06 14:00 UTC, RadhikaPPatel commented on src/midgard/pages/Custodians/forms/AddCustodians.js
> +let organization = localStorage.getItem("currentUser") ? JSON.parse(localStorage.getItem("currentUser")).organization.organization_uuid : '';
Same here

2021-01-06 14:01 UTC, RadhikaPPatel commented on src/midgard/pages/Dashboard/Dashboard.js
> +let organization = localStorage.getItem("currentUser") ? JSON.parse(localStorage.getItem("currentUser")).organization.organization_uuid : '';
Please do this change wherever more this appears.

2021-01-06 14:02 UTC, yasmin2496 commented on src/midgard/pages/Custodians/Custodians.js
> +let organization = localStorage.getItem("currentUser") ? JSON.parse(localStorage.getItem("currentUser")).organization.organization_uuid : '';
Have added the check as the front end was breaking for any non-logged in user. If someone visits the website for first time, without this check the view breaks.

2021-01-06 14:12 UTC, RadhikaPPatel commented on src/midgard/pages/Custodians/Custodians.js
> +let organization = localStorage.getItem("currentUser") ? JSON.parse(localStorage.getItem("currentUser")).organization.organization_uuid : '';
@yasmin2496 Not sure why it should break the login view. Can you please cross-check if there is a miss in the code somewhere? Because we are using the same approach in other UI repo and it works fine there.

2021-01-06 14:12 UTC, RadhikaPPatel requested changes
local storage current user check

2021-01-10 10:14 UTC, andrewshortall requested changes

2021-01-10 10:14 UTC, andrewshortall commented on src/midgard/pages/Custodians/Custodians.js
> +let organization = localStorage.getItem("currentUser") ? JSON.parse(localStorage.getItem("currentUser")).organization.organization_uuid : '';
I would like to remove the oauthUser and currentUser from local storage pretty soon. So I think defining `const organizationId = useContext(UserContext).organization.organization_uuid;` inside the function is a cleaner way of doing this. It should also eliminate the need for the ternary operator.

2021-01-11 14:36 UTC, yasmin2496 commented on src/midgard/pages/Custodians/Custodians.js
> +let organization = localStorage.getItem("currentUser") ? JSON.parse(localStorage.getItem("currentUser")).organization.organization_uuid : '';
Removed the local storage and replaced with `useContext`

2021-01-11 17:20 UTC, andrewshortall approved these changes

2021-01-12 05:21 UTC, RadhikaPPatel approved these changes

2021-01-12 05:24 UTC, merged