Fix map
TransparentPath/buildly-react-template pull request #494
Opened 2024-09-13 08:22 UTC by TanmayJain92

2024-09-17 10:25 UTC, patelradhika requested changes
Once I select a cluster and then click back to global view, I get empty map as shown in the screenshot.
![image](https://github.com/user-attachments/assets/e7e22036-f8bf-4c2d-96a6-2a1e58de1a87)

2024-09-17 10:25 UTC, patelradhika commented on src/pages/Shipment/Shipment.js
> +  console.log(shipmentData, rows);
Remove the console statement.

2024-09-17 14:18 UTC, TanmayJain92 commented on src/pages/Shipment/Shipment.js
> +  console.log(shipmentData, rows);
Done

2024-09-17 14:18 UTC, TanmayJain92 commented
Fixed above issues

2024-09-18 09:59 UTC, patelradhika approved these changes

2024-09-18 09:59 UTC, merged